apiVersion: v1
kind: Service
metadata:
  name: link-data-generator-app-service
  namespace: kafka-streams-windowing
  labels:
    app: link-data-generator-app-service
spec:
  type: NodePort
  selector:
    app: link-data-generator-app
  ports:
    - protocol: TCP
      port: 8020
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-data-generator-app
  namespace: kafka-streams-windowing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: link-data-generator-app
  template:
    metadata:
      labels:
        app: link-data-generator-app
    spec:
      containers:
        - name: link-data-generator-app
          env:
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              value: "kafka-service:9092"
          image: link-data-generator-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8020
