apiVersion: v1
kind: Service
metadata:
  name: tumbling-window-app-service
  namespace: kafka-streams-windowing
  labels:
    app: tumbling-window-app-service
spec:
  type: NodePort
  selector:
    app: tumbling-window-app
  ports:
    - protocol: TCP
      port: 8016
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tumbling-window-app
  namespace: kafka-streams-windowing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tumbling-window-app
  template:
    metadata:
      labels:
        app: tumbling-window-app
    spec:
      containers:
        - name: tumbling-window-app
          env:
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              value: "kafka-service:9092"
          image: tumbling-window-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8016
